// app/head.tsx
export default function Head() {
    return (
      <>
        <title>Dadaji Villa</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon-dadaji.ico" type="image/x-icon" />
      </>
    );
  }
   