import type { Metadata } from "next";
import './styles/fonts.scss';
import "./globals.css";
import Navigation from "./components/navigation";
import ScrollProgressCircle from "./components/ScrollProgressCircle/ScrollProgressCircle"
import Footer from "./components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <Navigation/>
        {children}
        <ScrollProgressCircle />
        <Footer/>
      </body>
    </html>
  );
}
